title: Heshima
email: heshima@celinedian.com
description: >- # this means to ignore newlines until "baseurl:"
  Heshima means Respect in Swahili and this underlies all that we do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

menu:
  - link: /
  - link: /WhatWeDo/History
  - link: /WhatWeDo/AboutUs
  - link: /Products/
  - link: /Newsletters/
  - link: /ContactUs/

defaults:
  - scope:
      path: ""
    values:
      layout: "single"

sass:
  style: compact
