title: Heshima
email: heshima@celinedian.com
description: >- # this means to ignore newlines until "baseurl:"
  Heshima means Respect in Swahili and this underlies all that we do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: heshima-org/weaver
plugins:
  - jekyll-feed
  - jekyll-remote-theme

menu:
  - link: /
  - link: /WhatWeDo/AboutUs
    menu:
      - link: /WhatWeDo/AboutUs
      - link: /WhatWeDo/History
      - link: /WhatWeDo/TextileTraining
      - link: /WhatWeDo/Preschool
  - link: /Products/
  - link: /SupportingHeshima/
    menu:
      - link: /SupportingHeshima/Volunteering
      - link: https://uk.virginmoneygiving.com/fundraiser-web/donate/makeDonationForCharityDisplay.action?charityId=1002097
        label: "Make a Donation"
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
